# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.
---

jobs:
    - name: update-projects
      job:
          type: decision-task
          treeherder-symbol: upd-proj
          target-tasks-method: update-projects
      when:
          - {hour: 0, minute: 0}
