# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

transforms:
    - l10n_taskgraph.update:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes: {}
    description: "Update {project} with translations."
    worker-type: linux
    worker:
        docker-image: {in-tree: l10n}
        max-run-time: 3600
    pr-target: main
    run:
        using: run-task
        cwd: '{checkout}'
        checkout:
            l10n:
                path: android-l10n
        command: ['import-android-l10n', 'android-l10n/{project}/l10n.toml', '{project}']

jobs:
    mozilla-lockwise/lockwise-android:
        repo-prefix: lockwise
        pr-target: master
    mozilla-mobile/android-components:
        repo-prefix: ac
        pr-target: master
    mozilla-mobile/fenix:
        repo-prefix: fenix
        pr-target: master
