# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

transforms:
    - l10n_taskgraph.update:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes: {}
    description: "Update {project} with translations."
    worker-type: linux
    worker:
        docker-image: {in-tree: l10n}
        max-run-time: 3600
    pr-target: main
    l10n-toml-path: android-l10n/{project}/l10n.toml
    run:
        using: run-task
        cwd: '{checkout}'
        checkout:
            l10n:
                path: android-l10n
        command: ['import-android-l10n', '{l10n_toml_path}', '{project}']

jobs:
    mozilla-mobile/android-components:
        repo-prefix: ac
        pr-target: main
    mozilla-mobile/fenix:
        repo-prefix: fenix
        pr-target: main
    mozilla-mobile/focus-android:
        repo-prefix: focusandroid
        pr-target: main
    mozilla-mobile/firefox-android/android-components:
        repo-prefix: firefoxandroid
        pr-target: main
        l10n-toml-path: 'android-l10n/mozilla-mobile/android-components/l10n.toml'
    mozilla-mobile/firefox-android/focus-android:
        repo-prefix: firefoxandroidfocus # TODO: Change to firefoxandroid after moving focus-android into the monorepo.
        pr-target: focus-prep # TODO: Change to main once we migrated focus-android over
        l10n-toml-path: 'android-l10n/mozilla-mobile/focus-android/l10n.toml'
