---
trust-domain: l10n
treeherder:
    group-names:
        'I': 'Docker Image Builds'

task-priority: lowest

github-token-secret: l10n/level-3/automation-bot-token

taskgraph:
    register: l10n_taskgraph:register
    repositories:
        tooling:
            name: "Android L10n Tooling"
            project-regex: android-l10n-tooling
            default-repository: https://github.com/mozilla-l10n/android-l10n-tooling
            default-ref: master
            type: git
        l10n:
            name: "Android L10n"
            project-regex: android-l10n$
            default-repository: https://github.com/mozilla-l10n/android-l10n
            default-ref: master
            type: git
        fenix:
            name: "Fenix"
            project-regex: fenix
            default-repository: https://github.com/mozilla-mobile/fenix
            default-ref: main
            type: git
        ac:
            name: "Android Components"
            project-regex: android-components
            default-repository: https://github.com/mozilla-mobile/android-components
            default-ref: main
            type: git
        focusandroid:
            name: "Focus Android"
            project-regex: focus-android
            default-repository: https://github.com/mozilla-mobile/focus-android
            default-ref: main
            type: git
        firefoxandroid:
            name: "Firefox Android"
            project-regex: firefox-android
            default-repository: https://github.com/mozilla-mobile/firefox-android
            default-ref: main
            type: git
    cached-task-prefix: l10n.android-l10n-tooling

workers:
    aliases:
        linux:
            provisioner: 'l10n-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'linux-gcp'
        images:
            provisioner: 'l10n-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'images-gcp'
