# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes: {}
    worker-type: linux
    worker:
        docker-image: {in-tree: base}
        max-run-time: 3600
    run:
        using: run-task
        cwd: '{checkout}'
        cache-dotcache: true
        checkout:
            l10n:
                path: android-l10n

jobs:
    reference-browser:
        description: ""
        run:
            checkout:
                rb:
                    path: mozilla-mobile/android-l10n

            command:
                create-l10n-branch --push ssh://github.com/Callek-bot/android-l10n --repo mozilla-mobile/android-components --branch android-components-quarantine android-l10n
